config/routes.rb
Rails.application.routes.draw do
  resources :product_photos
  get 'listings/index_my' => 'listings#index_my'
  get 'orders/index_request' => 'orders#index_request'
  get 'orders/accept' => 'orders#accept'
  get 'orders/deny' => 'orders#deny'
  get "orders/index_with_status" => "orders#index_with_status"

  resources :tags
  resources :orders
  resources :listings
  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'
  get 'welcome/about' => 'welcome#about' 

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :orders
  has_many :product_photos
  belongs_to :user
  acts_as_taggable
  validates :brand, :model, :condition, :start_time, :end_time, presence: true
  validates :price, presence: true,
  	numericality: {greater_than_or_equal_to: 0}

  has_attached_file :cover_photo
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/

  def delete
    update_attribute(:status, "inactive")
  end

  searchable do
    text :brand, :model, :tag_list, :description
    string :status
    latlon(:location) { Sunspot::Util::Coordinates.new(user.lat, user.lon) }
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /listings
  # GET /listings.json
  def index
    # @search = Listing.search do
    #   with(:status, 'active')
    #   fulltext params[:search]
    #   spellcheck :count => 3
    #   paginate :page => params[:page], :per_page => 9
    @listings = Listing.where("status = 'active' AND (brand LIKE ? OR model LIKE ? OR description LIKE ?)", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    if @listings.empty?
      @listings = Listing.tagged_with(params[:search].split(" "), :any => true).where("status = 'active'")
    end
    @listings = @listings.paginate(:page => params[:page], :per_page => 9)
  end

  def index_my
    @listings = current_user.listings
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @product_photos = ProductPhoto.where({ listing_id: @listing.id })

    if @listing.user_id == current_user.id
      @listing_orders = Order.where({ listing_id: @listing.id })
    end
    @comments_root = Comment.find_by_id(@listing.comment_root)
     @comments = @comments_root.hash_tree(limit_depth: 10)
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    @product_photos = ProductPhoto.where({ listing_id: @listing.id })
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @comment = Comment.new(title: 'root', author: 'nobody', body: 'empty')
    @comment.save
    @listing.comment_root = @comment.id

    respond_to do |format|
      if @listing.save

        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.delete
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:brand, :model, :price, :condition, :start_time, :end_time, :description, :user_id, :tag_list, :status, :cover_photo)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
	def cache_key_for_all_listings
  		"listing-table-#{Listing.maximum(:updated_at)}"
  	end

	def cache_key_for_each_listing_card(listing)
		"listing-card-#{listing.id}-#{listing.updated_at}"
	end

	def cache_key_for_each_listing(listing)
		"listing-#{listing.id}-#{listing.updated_at}"
	end

	def cache_key_for_each_listing_with_comment(listing, root)
		"listing-#{listing.id}-#{listing.updated_at}-#{root.updated_at}"
	end

	def cache_key_for_each_listing_photo(photo)
		"listing-photo-#{photo.id}-#{photo.updated_at}"
	end

	def cache_key_for_each_comment_tree(listing, root)
		"listing-comment-#{listing.id}-#{root.updated_at}"
	end

	def listing_cover_url(listing)
  	if listing.cover_photo.file?
  		listing.cover_photo.url
  	else 
  		"image_not_found.png"
  	end
	end

end

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <style>
  .d_avator{
      margin-top: 5px;
      margin-bottom: 5px;
      margin-left: 25px;
  }

  .Upload{
      font-weight: bold;
      vertical-align: text-bottom;
  }
  </style>

  <div class="form-group">
    <span class="glyphicon glyphicon-chevron-right"></span> <%= f.label :brand %>
    <%= f.text_field :brand, autofocus: true, class: "form-control input-md" %>
  </div>

  <div class="form-group">
    <span class="glyphicon glyphicon-chevron-right"></span> <%= f.label :model %>
    <%= f.text_field :model, autofocus: true, class: "form-control input-md" %>
  </div>

  <div class="form-group">
    <span class="glyphicon glyphicon-usd"> </span> <%= f.label :price %>
    <%= f.text_field :price, autofocus: true, class: "form-control input-md" %>
  </div>

  <div class="form-group">
  <span class="glyphicon glyphicon-wrench"> </span> <%= f.label :condition %> 
  <%= f.select(:condition, options_for_select(["Accceptable", "Good", "Like New"]), {}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <span class="glyphicon glyphicon-tag"> </span> <%= f.label(:tag_list, "Tags* (seperated by commas)") %>
    <%= f.text_field(:tag_list, value: @listing.tag_list.join(","), class: "form-control input-md") %>
  </div>

  <div class="form-group">
    <span class="glyphicon glyphicon-time"> </span> <%= f.label :start_time %>
    <%= f.text_field :start_time, :readonly => true, class: "form-control listing_start_time" %>
  </div>

  <div class="form-group">
    <span class="glyphicon glyphicon-time"> </span> <%= f.label :end_time %>
    <%= f.text_field :end_time, :readonly => true, class: "form-control listing_start_time" %>
  </div>

  <script>
    $(function() {
        $('.listing_start_time').datepicker({
          dateFormat: "yy-mm-dd",
          defaultDate: "0",
          minDate: "0",
          onSelect: function(date, inst){
            $( ".listing_end_time" ).datepicker("setDate", date);
            $( ".listing_end_time" ).datepicker("option", {minDate: date});
            setTimeout(function(){
              $( ".listing_end_time" ).datepicker('show');
            }, 16);   
          }
        });
      });

    $(function() {
      $('.listing_end_time').datepicker({
        dateFormat: "yy-mm-dd",
        minDate: "0"
      });
    });
  </script>

  <span class="glyphicon glyphicon-pencil"> </span> <%= f.label :description %><br>
  <%= f.text_area :description, class: "form-control", id: "textarea", rows: "3"%>

  <br>

  <div class="form-group">
    <span class="glyphicon glyphicon-picture"> </span> <b>Upload cover photo here!</b><br>
    <img id="img_prev" src="#" style="width:512px;height:400px;" onError="this.onerror=null;this.src='/images/default-thumb.png'" class="file-loading formal-control">
    <%= f.file_field :cover_photo, :onchange => "readURL(this);", class: 'Upload', id:'input-dim-2'%>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :status, :value => "active" %>
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/_show_photos.html.erb
<% if @listing.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

  <ul>
  <% @listing.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<!-- this block is for photos! -->
<% if @product_photos.size != 0  %>
  <table>
    <thead>
      <tr>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% @product_photos.each do |photo| %>
          <% cache(cache_key_for_each_listing_photo(photo)) do %>
          <td><%= image_tag  photo.picture.url, :size => '150'%></td>
          <% if (current_user.id == @listing.user_id ) %>
            <td><br><%= link_to 'Edit', edit_product_photo_path(photo, :listing => photo.listing_id), class:'btn btn-success' %></td>
          <% end %>
          <% end %> <!-- end cache -->
        <end>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p> We don't have any photos for this listing yet @_@! </p>
<% end %>

app/views/listings/edit.html.erb
<div class="container">
<div class="row">
<br> <br>
<h2>Editing Listing</h2>

	<%= render 'show_photos' %>
	<br>
	<td><%= link_to 'add pictures', new_product_photo_path(:listing => @listing.id), :class => 'btn btn-primary' %></td><br>
	<br>
	<%= render 'form' %>

	<%= link_to 'Show', @listing, :class => 'btn' %> |
	<%= link_to 'Back', listings_path, :class => 'btn'%>

</div>
</div>

app/views/listings/index.html.erb
<!doctype html>
<html lang="en">
<head>
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display|Raleway:700,100,400|Roboto:400,700|Playfair+Display+SC:400,700' rel='stylesheet' type='text/css'>
    <link href="/assets/css/hipster_cards.css" rel='stylesheet'>
    <link href="/assets/css/pe-icon-7-stroke.css" rel='stylesheet'>

    <style>
        .card{
            margin-bottom: 70px;
        }

        html, body {
          font-family: "Helvetica Neue","Open Sans",Arial,sans-serif;
          background-color: #e7e7e7;
        }
    </style>

</head>

<body>

<br><br><br>

<!-- <div class="wrapper"> -->
    <div class="container">

        <% if @listings.empty? %>
          <h2>Did you mean <%= link_to @suggestion, :controller => "listings", :search => @suggestion %>?</h2>
        <% else %>
          <%= will_paginate @listings %>
        
        <div class="masonry-container">

          <% @listings.each do |listing| %>
          <% cache(cache_key_for_each_listing_card(listing)) do %>
          <div class="card-box col-md-4 col-sm-6">

            <div class="card">

              <div class="header">
                <%= image_tag (listing_cover_url listing) %>

                <div class="actions">
                      <%= link_to 'More Details', listing, class:"btn btn-round btn-fill btn-neutral btn-modern",role:"button"  %>
                </div>

              </div>
            
              <div class="content">
                <h6 class="category"><%= listing.model %></h6>
                <h4 class="title"><a href="#"><%= listing.brand %></a></h4>

                <p class="description">
                  <% if listing.user_id != current_user.id %>
                    <%= link_to 'Order', new_order_path(:user => User.find(listing.user_id).id, :listing => listing.id) %>
                  <% else %>
                    <%= link_to 'Edit', edit_listing_path(listing) %>
                  <% end %>
                </p>
              </div>

            </div> <!-- end card -->

          </div> 
          <% end %> <!-- end cache -->
          <% end %>

        </div>    
        <% end %>
    </div>  
<!-- </div> end wrapper -->

</body>

  <script src="/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
  <script src="/assets/js/hipster-cards.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.min.js"></script>


</html>

app/views/listings/index_my.html.erb
<br>
<div class="container">
  <br>
  <h2>My Listings</h2>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        
        <thead>
          <tr>
            <th>Brand</th>
            <th>Model</th>
            <th>Price</th>
            <th>Condition</th>
            <th>Start time</th>
            <th>End time</th>
            <th>Status</th>
            <th>Owner Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @listings.each do |listing| %>
          <tr>
            <td><%= listing.brand %></td>
            <td><%= listing.model %></td>
            <td><%= listing.price %></td>
            <td><%= listing.condition %></td>
            <td><%= listing.start_time %></td>
            <td><%= listing.end_time %></td>
            <td><%= listing.status %></td>
            <td><%= current_user.email %></td>
            <td><%= link_to 'Show', listing %></td>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
       </tbody>

      </table>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<% cache do %>

<br>
<br>
<div class="container">
	<div class="row">
	<h2>New Listing</h2>

	<%= render 'form' %> 
	<br>
	<%= link_to 'Back', listings_path, class:'btn btn-success' %>

	</div>
</div>

<% end %>

app/views/listings/show.html.erb
<!DOCTYPE html>


<head>
    <style>
    footer {
        margin: 50px 0;
    }

    </style>

    <link href="/assets/css/show.css" rel='stylesheet'>
</head>

<body>
    <br>
    <br>
    <div class="container-fluid">
    <div class="content-wrapper">   
        <!-- <div class="item-container">     -->
            <div class="container"> 
                
                    <div class="col-md-12">
                        <%= image_tag (listing_cover_url @listing), height: "300" %>
                    </div>
                
                    <div class="col-md-7">
                    <div class="product-title"><%= @listing.brand %> <%= @listing.model %></div>
                    <div class="product-desc">Condition: <%= @listing.condition %></div>
                    
                    <hr>
                    <div class="product-price">$<%= @listing.price %></div>
                    <div class="product-stock">Duration: <%= @listing.start_time %> ~ <%= @listing.end_time %></div>
                    <div class="product-desc">Tags: <%= @listing.tag_list.join(', ') %></div>
                    <div class="product-desc">Owner: <%= User.find(@listing.user_id).email  %></div>
                    <div class="product-desc">Gadget location: <%= User.find(@listing.user_id).address  %></div>
                    <hr>

                    <% if @listing.user_id != current_user.id %>
                    <div class="btn-group cart">
                            <%= link_to 'Order', new_order_path(:user => User.find(@listing.user_id).id, :listing => @listing.id), class:"btn btn-success", type:"button"%> 
                    </div>
                    <% end %>
                </div>

            </div> 
        <!-- </div> -->
        <div class = "container">
        <div class = "row">
        <div class="container-fluid">       
            <div class="col-md-12 product-info">
                    <ul id="myTab" class="nav nav-tabs nav_tabs">
                        
                        <li class="active"><a href="#service-one" data-toggle="tab">Description</a></li>
                        <li><a href="#service-two" data-toggle="tab">Reviews</a></li>
                        <% if @listing.user_id == current_user.id %>
                        <li><a href="#service-three" data-toggle="tab">Orders</a></li>
                        <% end %>
                        <li><a href="#service-four" data-toggle="tab">Photos</a></li>

                    </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="service-one">
                        <section class="container product-info">
                            <%= @listing.description %>
                        </section>          
                    </div>

                    <div class="tab-pane fade" id="service-two">
                        <section class="container">
                        <% cache(cache_key_for_each_comment_tree(@listing, @comments_root)) do %>
                        <%= render template: 'comments/index' %> <br>
                        <% end %> <!-- cache end -->
                        </section>
                    </div>
                    
                    <% if @listing.user_id == current_user.id %>
                    <div class="tab-pane fade" id="service-three">
                        <section class="container">
                            <h2> Orders of this listing: </h2>
                            <table class="table table-striped">
                              <thead>
                                <tr>
                                  <th>Start time</th>
                                  <th>End time</th>
                                  <th>Status</th>
                                  <th>Price</th>
                                  <th colspan="5"></th>
                                </tr>
                              </thead>


                              <tbody>
                                <% @listing_orders.each do |order| %>
                                  <tr>
                                    <td><%= order.start_time %></td>
                                    <td><%= order.end_time %></td>
                                    <td><%= order.status %></td>
                                    <td><%= order.price %></td>
                                    <td><%= link_to 'Show', order %></td>
                                    <td><%= link_to 'Edit', edit_order_path(order) %></td>
                                    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    <% if order.status == "Processing" %>
                                    <td><%= link_to 'Accept', orders_accept_path(:order_id => order.id), data: { confirm: 'Are you sure?' } %></td>
                                    <td><%= link_to 'Deny', orders_deny_path(:order_id => order.id), data: { confirm: 'Are you sure?' } %></td>
                                    <% end %>
                                  </tr>
                                <% end %>
                              </tbody>
                            </table>                            
                        </section>
                    </div>
                    <% end %>

                    <div class="tab-pane fade" id="service-four">
                        <section class="container">
                            <%= render 'show_photos' %>
                        </section>
                    </div>


                </div>
                <hr>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

</body>


</html>