config/routes.rb
Rails.application.routes.draw do
  resources :product_photos
  get 'listings/index_my' => 'listings#index_my'
  get 'orders/index_request' => 'orders#index_request'
  get 'orders/accept' => 'orders#accept'
  get 'orders/deny' => 'orders#deny'
  get "orders/index_with_status" => "orders#index_with_status"

  resources :tags
  resources :orders
  resources :listings
  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'
  get 'welcome/about' => 'welcome#about' 

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
  validates :start_time, :end_time, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where({ user_id: current_user.id })
  end

  def index_request
    @my_listings = Listing.where({ user_id: current_user.id })
    @orders = Order.where({ listing_id: @my_listings.map(&:id) })
  end

  def index_with_status
    @my_listings = Listing.where({ user_id: current_user.id })
    if (params[:status] == "All")
      @orders = Order.where({ listing_id: @my_listings.map(&:id) })
    else
      @orders = Order.where({ listing_id: @my_listings.map(&:id), status: params[:status] })
    end
    render :partial => "index"
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @user = User.find(params[:user])
    @listing = Listing.find(params[:listing])
    @other_orders = Order.where({ listing_id: @listing.id })

    #ActionView::Base.debug_rjs = true
  end

  # GET /orders/1/edit
  def edit
    @listing = Listing.find(@order.listing_id);
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept
    @order = Order.find(params[:order_id])
    @order.update_attribute(:status, "Accepted")

  end

  def deny
    @order = Order.find(params[:order_id])
    @order.update_attribute(:status, "Denied")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:start_time, :end_time, :status, :price, :user_id, :listing_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def cache_key_for_each_order_row(order)
		"order-row-#{order.id}-#{order.updated_at}"
	end

	def cache_key_for_index_order(orders)
		"order_index-#{orders.maximum(:updated_at)}"
	end

end

app/views/orders/_form.html.erb
<h3>Listing Information:</h3>
<% cache(cache_key_for_each_listing(@listing)) do %>

<div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Listing Info
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="list-group">
                                <div class="list-group-item">
                                    <i class="fa fa-comment fa-fw"></i> Brand:
                                    <span class="pull-right text-muted small"><em><%= @listing.brand %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-twitter fa-fw"></i> Model:
                                    <span class="pull-right text-muted small"><em><%= @listing.model %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-envelope fa-fw"></i> Price:
                                    <span class="pull-right text-muted small"><em><%= @listing.price %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-tasks fa-fw"></i> Condition:
                                    <span class="pull-right text-muted small"><em><%= @listing.condition %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-upload fa-fw"></i> Tags:
                                    <span class="pull-right text-muted small"><em><%= @listing.tag_list.join(', ') %></p></em>
                                    </span>
                                </div>
                                <div class="list-group-item">
                                    <i class="fa fa-bolt fa-fw"></i> Listing Start time:
                                    <span class="pull-right text-muted small"><em><%= @listing.start_time %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-warning fa-fw"></i> Listing End time:
                                    <span class="pull-right text-muted small"><em><%= @listing.end_time %></em>
                                    </span>
    
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                  </div>


<% end %> <!-- end cache -->

<% cache do %>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <span class="glyphicon glyphicon-time"> </span> <%= f.label :start_time %>
    <%= f.text_field :start_time, :readonly => true, class: "form-control order_start_time" %>
  </div>

  <div class="form-group">
    <span class="glyphicon glyphicon-time"> </span> <%= f.label :end_time %>
    <%= f.text_field :end_time, :readonly => true, class: "form-control order_end_time" %>
  </div>

    <script>
    var selected_start_date = null;

    function start_and_end(){
      var start = JSON.parse("<%= raw escape_javascript Order.where('listing_id = ? AND id <> ?', @listing.id, @order.id).map(&:start_time).map {|t| t.strftime('%F') if (t!=nil)}.to_json %>");
      var end = JSON.parse("<%= raw escape_javascript Order.where('listing_id = ? AND id <> ?', @listing.id, @order.id).map(&:end_time).map {|t| t.strftime('%F') if (t!=nil)}.to_json %>");
      return {start: start, end: end};
    }

    function dateDisabled(date){
      var result = start_and_end();
      var start = result.start;
      var end = result.end;

      var len = start.length;
      //console.log(len);
      for(var i = 0; i < len; i++){
        //console.log(start[i]);
        //console.log(end[i]);
        //console.log(date);
        var d1 = new Date(start[i]);
        var d2 = new Date(end[i]);
        //console.log(d1);
        //console.log(d2);
        if (date >= d1 && date <= d2){
          //console.log("Oops");
          return [false, ""];
        }
      }
      return [true, ""];
    }

    function dateDisabled_end(date){
      if(dateDisabled(date)[0] == false)
        return [false, ""];

      var result = start_and_end();
      var start = result.start;
      var end = result.end;
      var len = start.length;
      var last_available = null;
      for(var i = 0; i < len; i++){
        var d1 = new Date(start[i]);
        if (d1 > selected_start_date &&
          (last_available == null || last_available > d1)){
          last_available = d1;
        }
      }

      if(last_available == null || date < last_available)
        return [true, ""];
      else
        return [false, ""];
    }

    $(function() {
      $(".order_start_time").datepicker({
        dateFormat: "yy-mm-dd",
        defaultDate: "0",
        minDate: "0",
        maxDate: "<%= Listing.find(@listing.id).end_time %>",
        beforeShowDay: dateDisabled,
        onSelect: function(date, inst){
          selected_start_date = new Date(date);
          $( ".order_end_time" ).datepicker("setDate", date);
          $( ".order_end_time" ).datepicker("option", {minDate: date});
          $( ".order_end_time" ).datepicker("option", {beforeShowDay: dateDisabled_end});
          setTimeout(function(){
            $( ".order_end_time" ).datepicker('show');
          }, 16);   
        }
      });
    });

    $(function() {
      //$('.order_end_time').removeClass('hasDatepicker');

      $(".order_end_time").datepicker({
        dateFormat: "yy-mm-dd", 
        minDate: "0",
        maxDate: "<%= Listing.find(@listing.id).end_time %>",
        beforeShowDay: dateDisabled
      });
    });
   </script>

  </div>
  <%= f.hidden_field :price, :value => @listing.price %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :listing_id, :value => @listing.id %>
    <%= f.hidden_field :status, :value => "Processing" %>
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-lg btn-success btn-block' %>
  </div>
<% end %>

<% end %> <!-- cache end -->

app/views/orders/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Status</th>
      <th>Price</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= User.find(Listing.find(order.listing_id).user_id).email %></td>
        <td><%= order.start_time %></td>
        <td><%= order.end_time %></td>
        <td><%= order.status %></td>
        <td><%= order.price %></td>
        <td><%= link_to 'Show', order %></td>

        <% if order.status == "Processing" %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

        <% if order.status == "Processing" %>
        <td><%= link_to 'Accept', orders_accept_path(:order_id => order.id), data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Deny', orders_deny_path(:order_id => order.id), data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/accept.html.erb
<div class="container">
<div class="row">
<br><br>
<h2>Order Accepted</h2>

<%= render :file => 'orders/show' %>


</div>
</div>

app/views/orders/deny.html.erb
<h2>Order Denied</h2>

<%= render :file => 'orders/show' %>

<%= link_to 'Back', orders_index_request_path %>

app/views/orders/edit.html.erb
<div class="container">
<div class="row">

<br><br>
<h2>Editing Order</h2>

<%= render 'form' %>
<br>
<%= link_to 'Show', @order, class:"btn btn-lg btn-success btn-block" %> 
<br>
<%= link_to 'Back', orders_path, class:"btn btn-lg btn-success btn-block"%>
</div>
</div>

app/views/orders/index.html.erb
<% cache(cache_key_for_index_order(@orders)) do %>
<div class="container">
  <br>
  <br>
  <h2>My Orders</h2>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        
        <thead>
          <tr>
            <th>Owner</th>
            <th>Start time</th>
            <th>End time</th>
            <th>Status</th>
            <th>Price</th>
            <th colspan="5"></th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <% cache(cache_key_for_each_order_row(order)) do %>
              <tr>
              <td><%= User.find(Listing.find(order.listing_id).user_id).email %></td>
              <td><%= order.start_time %></td>
              <td><%= order.end_time %></td>
              <td><%= order.status %></td>
              <td><%= order.price %></td>
              <td><%= link_to 'Show', order %></td>
              <% if order.status == "Processing" %>
              <td><%= link_to 'Edit', edit_order_path(order) %></td>
              <td><%= link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure you want to CANCEL this order?' } %></td>
              <% end %>
              </tr>
            <% end %> <!-- cache end -->
          <% end %>
       </tbody>
      </table>
    </div>
  </div>
</div>
<% end %> <!-- cache end -->

app/views/orders/index_request.html.erb
<br>
<br>
<div class="container">
  <div class="row">
  <p id="notice"><%= notice %></p>

  <h2>Order request</h2>

  <script>
    function update_status_div(status) {  
      //console.log("wow");
    jQuery.ajax({
      url: "index_with_status",
      type: "GET",
      data: {"status" : status},
      dataType: "html",
      success: function(data) {
        //console.log("aha");
        jQuery("#ordersDiv").html(data);
      }
    });
  }
  </script>

 <%= select_tag 'status', options_for_select(["All", "Accepted", "Denied", "Processing"], "All"), class:"form-control", :onchange => "update_status_div(this.value)" %>

  <br>

  <div id="ordersDiv">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Requester</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Status</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= User.find(order.user_id).email %></td>
        <td><%= order.start_time %></td>
        <td><%= order.end_time %></td>
        <td><%= order.status %></td>
        <td><%= order.price %></td>
        <td><%= link_to 'Show', order %></td>

        <% if order.status == "Processing" %>
        <td><%= link_to 'Accept', orders_accept_path(:order_id => order.id), data: { confirm: 'Accept this order?' } %></td>
        <td><%= link_to 'Deny', orders_deny_path(:order_id => order.id), data: { confirm: 'Deny this order?' } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
</div>
</div>

app/views/orders/new.html.erb
<div class="container">
	<div class="row">
	<br><br>
	<h2>New Order</h2>

	<%= render 'form' %>
	<br>
	<%= link_to 'Back', orders_path, class:"btn btn-lg btn-success btn-block" %>


	</div>
</div>

app/views/orders/show.html.erb
<div class="container">
	<br><br>
	<div class="row">
	<p id="notice"><%= notice %></p>
	<br>

	<div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Listing Info
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="list-group">
                                <div class="list-group-item">
                                    <i class="fa fa-comment fa-fw"></i> Owner:
                                    <span class="pull-right text-muted small"><em><%= User.find(Listing.find(@order.listing_id).user_id).email %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-twitter fa-fw"></i> Owner location:
                                    <span class="pull-right text-muted small"><em><%= User.find(Listing.find(@order.listing_id).user_id).address %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-envelope fa-fw"></i> Requester:
                                    <span class="pull-right text-muted small"><em><%= User.find(@order.user_id).email %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-tasks fa-fw"></i> Requester location:
                                    <span class="pull-right text-muted small"><em><%= User.find(@order.user_id).address %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-upload fa-fw"></i> Start time:
                                    <span class="pull-right text-muted small"><em><%= @order.start_time %></em>
                                    </span>
                                </div>
                                <div class="list-group-item">
                                    <i class="fa fa-bolt fa-fw"></i> End time:
                                    <span class="pull-right text-muted small"><em><%= @order.end_time %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-warning fa-fw"></i> Status:
                                    <span class="pull-right text-muted small"><em><%= @order.status %></em>
                                    </span>
                                </div>
                                <div href="#" class="list-group-item">
                                    <i class="fa fa-shopping-cart fa-fw"></i> Price:
                                    <span class="pull-right text-muted small"><em><%= @order.price %></em>
                                    </span>
                                </div>
    
                            </div>
                            <!-- /.list-group -->
                            <%= link_to 'Edit', edit_order_path(@order), class:"btn btn-lg btn-success btn-block"%><br>
                            <%= link_to 'Review Listing', listing_path(@order.listing_id), class:"btn btn-lg btn-success btn-block" %>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
	</div>
</div>