config/routes.rb
Rails.application.routes.draw do
  resources :product_photos
  get 'listings/index_my' => 'listings#index_my'
  get 'orders/index_request' => 'orders#index_request'
  get 'orders/accept' => 'orders#accept'
  get 'orders/deny' => 'orders#deny'
  get "orders/index_with_status" => "orders#index_with_status"

  resources :tags
  resources :orders
  resources :listings
  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'
  get 'welcome/about' => 'welcome#about' 

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

end

app/models/product_photo.rb
class ProductPhoto < ActiveRecord::Base
	belongs_to :listing
	
	has_attached_file :picture
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/controllers/product_photos_controller.rb
class ProductPhotosController < ApplicationController
  before_action :set_product_photo, only: [:show, :edit, :update, :destroy]

  # GET /product_photos
  # GET /product_photos.json
  def index
    @product_photos = ProductPhoto.all
  end

  # GET /product_photos/1
  # GET /product_photos/1.json
  def show
  end

  # GET /product_photos/new
  def new
    @product_photo = ProductPhoto.new
    @listing = Listing.find(params[:listing])
  end

  # GET /product_photos/1/edit
  def edit
    @listing = Listing.find(params[:listing])
  end

  # POST /product_photos
  # POST /product_photos.json
  def create
    @product_photo = ProductPhoto.new(product_photo_params)

    respond_to do |format|
      if @product_photo.save
        format.html { redirect_to @product_photo, notice: 'Product photo was successfully created.' }
        format.json { render :show, status: :created, location: @product_photo }
      else
        format.html { render :new }
        format.json { render json: @product_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_photos/1
  # PATCH/PUT /product_photos/1.json
  def update
    respond_to do |format|
      if @product_photo.update(product_photo_params)
        format.html { redirect_to @product_photo, notice: 'Product photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_photo }
      else
        format.html { render :edit }
        format.json { render json: @product_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_photos/1
  # DELETE /product_photos/1.json
  def destroy
    @product_photo.destroy
    respond_to do |format|
      format.html { redirect_to product_photos_url, notice: 'Product photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_photo
      @product_photo = ProductPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_photo_params
      params.require(:product_photo).permit(:description, :listing_id, :picture)
    end
end

app/helpers/product_photos_helper.rb
module ProductPhotosHelper
end

app/views/product_photos/_form.html.erb
<%= form_for(@product_photo) do |f| %>
  <% if @product_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_photo.errors.count, "error") %> prohibited this product_photo from being saved:</h2>

      <ul>
      <% @product_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
    <%= f.hidden_field :listing_id, :value => @listing.id %>
    <div>
      <img id="img_prev" src="#" onError="this.onerror=null;this.src='/images/default-thumb.png';" 
      style="width:512px;height:400px;">
      <%= f.file_field :picture, :onchange => "readURL(this);" %>
    </div>

  </div><br>
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/product_photos/edit.html.erb
<div class="container">
<div class="row">
	<br><br>
<h2>Editing Product Photo</h2>

<%= render 'form' %>

<br>
<%= link_to 'Back', listing_path(params[:listing]), class:"btn btn-primary"%> 
<br>
<br>
<%= link_to 'Destroy', product_photo_path, class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
</div>

app/views/product_photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Photos</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_photos.each do |product_photo| %>
      <tr>
        <td><%= product_photo.description %></td>
        <td><%= link_to 'Show', product_photo %></td>
        <td><%= link_to 'Edit', edit_product_photo_path(product_photo) %></td>
        <td><%= link_to 'Destroy', product_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Product photo', new_product_photo_path %> -->

app/views/product_photos/new.html.erb
<div class="container">
<div class="row">
	<br><br>
<h2>Add a new photo for your product!</h2>

<%= render 'form' %>

<!-- need a better path = =... -->
<br>
<%= link_to 'Back', listing_path(params[:listing]), class:"btn btn-primary" %>
</div>
</div>

app/views/product_photos/show.html.erb
<div class="container">
<div class="row">
<br> <br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @product_photo.description %>
</p>
<%= image_tag @product_photo.picture.url , :size => '150'%>

<%= link_to 'Back', listing_path(@product_photo.listing_id), class:'btn btn-success' %>
</div>
</div>