config/routes.rb
Rails.application.routes.draw do
  resources :product_photos
  get 'listings/index_my' => 'listings#index_my'
  get 'orders/index_request' => 'orders#index_request'
  get 'orders/accept' => 'orders#accept'
  get 'orders/deny' => 'orders#deny'
  get "orders/index_with_status" => "orders#index_with_status"

  resources :tags
  resources :orders
  resources :listings
  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'
  get 'welcome/about' => 'welcome#about' 

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Gadgetbite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<style type="text/css">
.avatar-frame{border: 5px solid #F8F8F8;}
.avatar-frame,.avatar-frame img{
  width: 40px;
  height: 40px;
  -webkit-border-radius: 30px; /* Saf3+, Chrome */
  border-radius: 30px; /* Opera 10.5, IE 9 */
  /*-moz-border-radius: 30px;  Disabled for FF1+ */
  }

.lsearch{
  margin-top: 10px;
  margin-left: 10px;
  margin-bottom: 0px;
}
</style>
  

</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="/">Gadgetbite</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li><a href="/">Home</a></li>
            <li><a href="/welcome/about">About</a></li>
            
            
            <li class="lsearch">
            <div class="form-group">
              <%= form_tag listings_path, :method => :get do %>
              <%= text_field_tag :search, params[:search], :class => "form-control", :type => "text" %>
            </div>
            </li>

            <li class="lsearch">
              <%= submit_tag "Search", :class => "btn btn-default", :type=> "submit", :name => nil %>
              <% end %>
            </li>
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li><%= link_to 'Add Listing', new_listing_path %></li>
                <li><%= link_to 'My Listings', listings_index_my_path %></li>
                <li><%= link_to 'My Orders', orders_path %></li>
                <li><%= link_to 'Order Requests', orders_index_request_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
              </ul>
            </li>
            <li><div class="avatar-frame"><a href=<%= edit_user_registration_path %>>
                <%= image_tag (user_photo_url current_user), :size => '150'%>
            </a></div></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path%></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
        
        <br>
        <%= yield %>
        <br>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="/welcome/about">About</a>
                        </li>
                        <!-- <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li> -->
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; BiteMi 2015. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>